/*
    R: Sempre que executamos uma função no JavaScript, 
    ela é associada a um contexto de execução. 
    Esse contexto possui uma propriedade denominada ThisBinding, 
    que pode ser acessada a qualquer momento através da palavra reservada this. O valor do this, que chamamos de contexto da função, é constante e existe enquanto este contexto de execução existir. Toda função também declarada no escopo 
    global possui o objeto window como valor do this.
*/