/*
R: No JavaScript, 
a declaração das nossas funções e variáveis 
possuem o comportamento de Hoisting.
 Este nome é dado ao comportamento de mover declarações para o topo de um escopo (global ou não). Em outras palavras, isso significa que é possível usar uma variável ou função antes mesmo de declará-las no código. No ES6, o “hoisting” do let e const são diferentes de variáveis e funções. Quando uma variável é declarada usando let ou const , ela possui o que é chamada de Temporal Dead Zone (TDZ), nome que descreve o comportamento de que, no seu escopo, ela é inacessível 
até que a execução alcance sua declaração
*/ 