/*
R: Funções geradoras são funções no JavaScript em que podemos 
interromper e retornar sua execução várias vezes. Em termos práticos, 
isso significa que a execução do método é realizada até um ponto e é interrompida 
até que invocada novamente. Quando invocada, continua sua execução a partir do ponto em que parou. 
Essas funções são identificadas pela presenta do * (asterisco) em sua declaração e da palavra 
reservada yield em sua implementação.
*/ 