/*
R: O JavaScript Object Notation (JSON) é um formato leve,
criado como subconjunto da notação de objetos
literais do JavaScript, para troca de dados.
Originalmente criado por Douglas Crockford,
o formato que é reconhecido devido a sua simplicidade e flexibilidade, não é usado somente no JavaScript, mas na maior parte das linguagens de programação voltadas para web. Ele é muito semelhante a um objeto literal e devido a sua simplicidade,
tem sido usado por muitas empresas para criar APIs REST.

*/ 