/*
R: Este nome foi dado para a situação na qual temos várias chamadas assíncronas 
que dependem uma da outra. Como as operações assíncronas ocorrem simultaneamente e 
respondem em tempos diferentes, torna-se uma tarefa extremamente árdua para o desenvolver 
entender o que acontece na execução deste código. As Promises foram criadas para que o 
desenvolvedor 
possa lidar melhor com as inúmeras chamadas assíncronas no código.
*/